add requester_pays boolean argument to all S3 requests
andersfugmann/aws-s3 pull request #25
Opened 2022-04-05 23:55 UTC by barko

2022-04-06 20:43 UTC, andersfugmann requested changes
Thanks for the PR.
Some comments on the naming on the flag and extending the documentation but otherwise ok.

Thanks for submitting.

2022-04-06 20:43 UTC, andersfugmann commented on aws-s3/s3.ml
> +  let add_request_payer headers = function
As I understand the API, this header must be present on calls to buckets where the requested acknowledges that the requester will be charged for the request. 

The name `request_payer` seems not to reflect this. I suggest renaming this to `confirm_requester_pays`, in line with the documentation.

The function here acually only adds the header if the second argument is true, so it should be named `maybe_...`. Also flipping the two arguments makes it easier to chain calls using the pipe (`|>`) operator.

2022-04-06 20:43 UTC, andersfugmann commented on aws-s3/s3.ml
> +  let put_common ?credentials ?connect_timeout_ms ?(requester_pays=false) ~endpoint ?content_type ?content_encoding ?acl ?cache_control ?expect ~bucket ~key ~body () =
As mentioned before, the argument name is misleading.

2022-04-06 20:43 UTC, andersfugmann commented on aws-s3/s3.mli
> +  (* If [requester_pays], caller will pay AWS data transfer costs. *)
This is not in line with the documentation. When operating on `Requester Pays buckets`, a special header must be present to indicate the callers willingness to accept charges. Setting the flag on non-requester pays bucket has no effect, and not setting the flag on requester-pays buckets, wil case any operation to fail (unless the caller owns the bucket).

2022-04-06 20:43 UTC, andersfugmann commented on cli/cli.ml
> +    Arg.(value & opt int 0 & info ["retries"] ~docv:"RETRIES" ~doc)
Nice catch. Thanks

2022-04-06 20:43 UTC, andersfugmann commented on cli/cli.ml
> +    let doc = "indicate that the client is paying for the request" in
Again, I think this is not in line with what this flag actually means.

2022-04-06 20:43 UTC, andersfugmann commented on aws-s3/s3.mli
> +  (* If [requester_pays], caller will pay AWS data transfer costs. *)
Maybe add a link to the [documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ObjectsinRequesterPaysBuckets.html) in the documentation comment for the flag.

2022-04-06 20:44 UTC, andersfugmann commented
The PR seems to have conflicts after recent changes. Would you be able to rebase on master?

2022-04-07 01:23 UTC, barko commented
Thanks for the many suggestions. I believe that I adopted all of them in new PR #27 .

2022-04-07 01:23 UTC, closed without merging